const continental = {
	countries: {
		afghanistan: {
			name: "Afghanistan",
			populationN: 41984070,
			populationW: "41.98M",
			area: "652,860 km²",
			map: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_map_of_Afghanistan.png",
			capital: "Kabul",
			languages: ["Dari", "Pashto"],
			religion: "Islam",
			cities: ["Kabul", "Kandahar", "Herat"],
			dish: "Kabuli",
		},
		albania: {
			name: "Albania",
			populationN: 2877000,
			populationW: "2.87M",
			area: "27,400 km²",
			map: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Flag-map_of_Albania.svg/1200px-Flag-map_of_Albania.svg.png",
			capital: "Tirana",
			languages: ["Albanian"],
			religion: "Islam",
			cities: ["Tirana", "Durres", "Elbasan"],
			dish: "Tavë kosi",
		},
		algeria: {
			name: "Algeria",
			populationN: 43851044,
			populationW: "43.85M",
			area: "2,381,740 km²",
			map: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_Map_of_Algeria.png",
			capital: "Algiers",
			languages: ["Arabic", "Tamazight (Berber)"],
			religion: "Islam",
			cities: ["Algiers", "Boumerdas", "Oran"],
			dish: "Couscous",
		},
		andorra: {
			name: "Andorra",
			populationN: 77265,
			populationW: "77.2K",
			area: "470 km²",
			map: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_map_of_Andorra.svg/1200px-Flag_map_of_Andorra.svg.png",
			capital: "Andorra La Vella",
			languages: ["Catalan"],
			religion: "Catholic Christianity",
			cities: ["Andorra La Vella", "les Escaldes", "Encamp"],
			dish: "Escudella",
		},
		angola: {
			name: "Angola",
			populationN: 32866272,
			populationW: "32.86M",
			area: "1,246,700 km²",
			map: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag-map_of_Angola.svg/911px-Flag-map_of_Angola.svg.png",
			capital: "Luanda",
			languages: ["Portuguese"],
			religion: "Protestant / Catholic Christianity",
			cities: ["Luanda", "N'dalatando", "Huambo"],
			dish: "Muamba de Galinha",
		},
		antiguaandbarbuda: {
			name: "Antigua and Barbuda",
			populationN: 100023,
			populationW: "100.02K",
			area: "440 km²",
			map: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag-map_of_Antigua_and_Barbuda.png",
			capital: "Saint John's",
			languages: ["English", "Spanish"],
			religion: "Christianity",
			cities: ["Saint John's", "All Saints", "Piggotts"],
			dish: "Fungee and Pepperpot",
		},
		argentina: {
			name: "Argentina",
			populationN: 45195774,
			populationW: "45.19M",
			area: "2,736,690 km²",
			map: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_map_of_Argentina.svg/624px-Flag_map_of_Argentina.svg.png?20230402025017",
			capital: "Buenos Aires",
			languages: ["Spanish"],
			religion: "Christianity",
			cities: ["Buenos Aires", "Cordoba", "Rosario"],
			dish: "Asado",
		},
		armenia: {
			name: "Armenia",
			populationN: 2963243,
			populationW: "2.96M",
			area: "28,470 km²",
			map: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_map_of_Armenia.svg/1200px-Flag_map_of_Armenia.svg.png",
			capital: "Yerevan",
			languages: ["Spanish"],
			religion: "Christianity",
			cities: ["Buenos Aires", "Cordoba", "Rosario"],
			dish: "Asado",
		},
	}
}
